repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo02
repo_name: 2025.2-Grupo02

site_name: Projeto Grupo 02

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    # Paleta para o modo claro
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro

    # Paleta para o modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

markdown_extensions:
  - toc:
      permalink: true
  - attr_list

nav:
  - Home: index.md

  - Planejamento:
      - Guias:
          - Contribuição: 01_planejamento/guias/contribuicao.md
          - Ata Padrão: 01_planejamento/guias/ata_padrao.md
      - Cronograma: 01_planejamento/cronograma.md
      - Cronograma Executado: 01_planejamento/cronograma_executado.md
      - Aplicativo Escolhido: 01_planejamento/aplicativo_escolhido.md
      - Ferramentas: 01_planejamento/ferramentas.md
      - Heatmap: 01_planejamento/heatmap.md

  - Pré-rastreabilidade:
      - Rich Picture: 02_pre-rastreabilidade/rich_picture.md

  - Elicitação:
      - Artefatos:
          - Glossário: 03_elicitacao/artefatos/glossario.md
          - Perfil de usuário: 03_elicitacao/artefatos/perfil_usuario.md
          - Requisitos Elicitados: 03_elicitacao/artefatos/requisitos_elicitados.md
          - Requisitos Não Implementados: 03_elicitacao/artefatos/requisitos_nao_implementados.md
      - Técnicas:
          - Análise de Documentos: 03_elicitacao/tecnicas/analise_documentos.md
          - Entrevista: 03_elicitacao/tecnicas/entrevista.md
          - Observação: 03_elicitacao/tecnicas/observacao.md

  - Priorização:
      - In or Out: 04_priorizacao/in_or_out.md
      - MoSCoW: 04_priorizacao/moscow.md
      - Pairwise Comparison: 04_priorizacao/pairwise_comparison.md
      - Three Level Scale: 04_priorizacao/three_level_scale.md

  - Modelagem:
      - Cenários: 05_modelagem/01_cenarios/cenarios.md
      - Léxicos: 05_modelagem/02_lexicos/lexicos.md
      - Casos de Uso: 05_modelagem/03_casos_de_uso/casos_de_uso.md
      - Especificação Suplementar: 05_modelagem/04_especificacao_suplementar/especificacao_suplementar.md
      - Agil:
          - Histórias de Usuário: 05_modelagem/05_Agil/01_historias_de_usuario.md
          - Backlogs: 05_modelagem/05_Agil/02_backlogs.md
          - NFR Framework: 05_modelagem/05_Agil/03_nfr_framework.md

  - Pós-rastreabilidade:
        - Matrizes:
            - Backward-from: 06_pos-rastreabilidade/matrizes/01_backward_from.md
            - Forward-from: 06_pos-rastreabilidade/matrizes/02_forward_from.md
        - Elos de Pós-Rastreabilidade: 06_pos-rastreabilidade/elos_de_rastreabilidade.md
        - Matriz de Pós-Rastreabilidade: 06_pos-rastreabilidade/matriz_de_rastreabilidade.md

  - Verificação:
      - Entrega 1:
          - Rich Picture: 07_verificacao/entrega1/verificacao_rich_picture.md
      - Entrega 2:
          - Elicitação:
              - Artefatos:
                  - Glossário: 07_verificacao/entrega2/01_elicitacao/artefatos/verificacao_glossario.md
                  - Perfil de usuário: 07_verificacao/entrega2/01_elicitacao/artefatos/verificacao_perfil_de_usuario.md
              - Técnicas:
                  - Análise de Documentos: 07_verificacao/entrega2/01_elicitacao/tecnicas/verificacao_analise_de_documentos.md
                  - Brainstorming: 07_verificacao/entrega2/01_elicitacao/tecnicas/verificacao_brainstorming.md
                  - Entrevista: 07_verificacao/entrega2/01_elicitacao/tecnicas/verificacao_entrevista.md
                  - Observação: 07_verificacao/entrega2/01_elicitacao/tecnicas/verificacao_observacao.md
          - Priorização:
              - In or Out: 07_verificacao/entrega2/02_priorizacao/verificacao_in_or_out.md
              - MoSCoW: 07_verificacao/entrega2/02_priorizacao/verificacao_MoSCoW.md
              - Pairwise Comparison: 07_verificacao/entrega2/02_priorizacao/verificacao_pairwise_comparison.md
              - Three Level Scale: 07_verificacao/entrega2/02_priorizacao/verificacao_three_level_scale.md
      - Entrega 3:
          - Cenários: 07_verificacao/entrega3/01_cenarios/verificacao_cenarios.md
          - Léxicos: 07_verificacao/entrega3/02_lexicos/verificacao_lexicos.md
          - Casos de Uso: 07_verificacao/entrega3/03_casos_de_uso/verificacao_casos_de_uso.md
          - Especificação Suplementar: 07_verificacao/entrega3/04_especificacao_suplementar/verificacao_especificacao_suplementar.md
      - Entrega 4:
          - Histórias de Usuário: 07_verificacao/entrega4/verificacao_historias_de_usuario.md
          - Backlogs: 07_verificacao/entrega4/verificacao_backlogs.md
          - NFR Framework: 07_verificacao/entrega4/verificacao_nfr_framework.md
      - Entrega 5:
          - Elos de Rastreabilidade: 07_verificacao/entrega5/verificacao_elos_de_rastreabilidade.md
          - Elos de Rastreabilidade Inspeção Geral grupo 2: 07_verificacao/entrega5/verficacao_elos_geral_grupo2.md
          - Elos de Rastreabilidade Inspeção Geral grupo 3: 07_verificacao/entrega5/verficacao_elos_geral_grupo3.md

  - Inspeção:
      - Entrega 1:
          - Inspeção Geral: 08_inspecao/entrega1/inspecao_grupo_mais_um.md
          - Rich Picture: 08_inspecao/entrega1/inspecao_richpicture.md
      - Entrega 2:
          - Elicitação:
              - Artefatos:
                  - Glossário: 08_inspecao/entrega2/01_elicitacao/artefatos/inspecao_glossario.md
                  - Perfil de usuário: 08_inspecao/entrega2/01_elicitacao/artefatos/inspecao_perfil_de_usuario.md
              - Técnicas:
                  - Análise de Documentos: 08_inspecao/entrega2/01_elicitacao/tecnicas/inspecao_analise_de_documentos.md
                  - Brainstorming: 08_inspecao/entrega2/01_elicitacao/tecnicas/inspecao_brainstorming.md
                  - Entrevista: 08_inspecao/entrega2/01_elicitacao/tecnicas/inspecao_entrevista.md
                  - Observação: 08_inspecao/entrega2/01_elicitacao/tecnicas/inspecao_observacao.md
          - Priorização:
              - In or Out: 08_inspecao/entrega2/02_priorizacao/inspecao_in_or_out.md
              - MoSCoW: 08_inspecao/entrega2/02_priorizacao/inspecao_MoSCoW.md
              - Pairwise Comparison: 08_inspecao/entrega2/02_priorizacao/inspecao_pairwise_comparison.md
              - Three Level Scale: 08_inspecao/entrega2/02_priorizacao/inspecao_three_level_scale.md
          - Inspeção Geral: 08_inspecao/entrega2/inspecao_geral.md
      - Entrega 3:
          - Inspeção Geral: 08_inspecao/entrega3/inspecao_geral.md
          - Inspeção Geral Grupo 2: 08_inspecao/entrega3/inspecao_geral_grupo2.md
          - Inspeção Cenários: 08_inspecao/entrega3/inspecao_cenarios.md
          - Inspeção Léxicos: 08_inspecao/entrega3/inspecao_lexicos.md
          - Inspeção Casos de Uso: 08_inspecao/entrega3/inspecao_casos_de_uso.md
          - Inspeção Especificação Suplementar: 08_inspecao/entrega3/inspecao_especificacao_suplementar.md
      - Entrega 4:
          - Inspeção Geral Grupo 2: 08_inspecao/entrega4/01_inspecao_geral_grupo2.md
          - Inspeção Geral Grupo +1: 08_inspecao/entrega4/02_inspecao_geral_grupo3.md
          - Inspeção Histórias de Usuário: 08_inspecao/entrega4/03_inspecao_historia_de_usuarios.md
          - Inspeção Backlogs: 08_inspecao/entrega4/04_inspecao_backlogs.md
          - Inspeção NFR Framework: 08_inspecao/entrega4/05_inspecao_nfr.md
      - Entrega 5:
          - Inspeção Geral Grupo 2: 08_inspecao/entrega5/01_inspecao_geral_grupo2.md
          - Inspeção Geral Grupo +1: 08_inspecao/entrega5/02_inspecao_geral_grupo3.md
          - Inspeção Elos de Rastreabilidade Grupo 2: 08_inspecao/entrega5/03_inspecao_elos_de_rastreabilidade_grupo2.md
          - Inspeção Elos de Rastreabilidade Grupo +1: 08_inspecao/entrega5/04_inspecao_elos_de_rastreabilidade_grupo3.md

  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
      - Apresentação 3: apresentacao/apresentacao3.md
      - Apresentação 4: apresentacao/apresentacao4.md

  - Documentação:
      - Atas de Reunião:
          - Ata 1: atas/ata1.md
          - Ata 2: atas/ata2.md
          - Ata 3: atas/ata3.md
